### ISSUE TITLE
Something missing from all of your online resources...

### ISSUE THREAD

**Issue by atomize** [hkamran/Hoones#1]
...is a way to contact you besides submitting a github issue =) You've gotta be the only dev with some sweet code on github and nary even a twitter handle ! I have no issue with Hoones but am interested in a potential fork for specific purposes but had some questions. Got some contact info?

**Comment by hkamran** [comment]
Sure, you can contact me at hoodev490 [at] gmail.com

**Comment by atomize** [comment]
Thanks! Cheers! Chat soon.
